### ISSUE TITLE
OrderSearchRequest interface's "ids" property needs to accept an array

### ISSUE THREAD

**Issue by palbrecht1** [denkan/gelato-api#1]
Hi,

Thanks a lot for providing this repository, it's very helpful.

When you hit the order search endpoint, gelato allows you to provide a list of IDs, passed as an array, as stated in [this doc](https://dashboard.gelato.com/docs/orders/v3/search/).

The current interface "OrderSearchRequest" only allows ids to be a string, so we cannot do a search by IDs.

We need to update the interface to allow an array of string.

**Comment by denkan** [comment]
Absolutely right, thank you for contributing!
Merged PR and published updates to NPM.
