### ISSUE TITLE
NPM doesn't seem to have the re-built version of 1.0.4

### ISSUE THREAD

**Issue by palbrecht1** [denkan/gelato-api#3]
Somehow pulling gelato-api@1.0.4 doesn't have the bugfix for #1 

How to reproduce:
npm init
npm install gelato-api@1.0.4
cd ./node_modules/gelato-api/dist
cat types.d.ts

![image](https://user-images.githubusercontent.com/53092932/157495800-7afb7b6e-f83b-4641-b019-36d1724407d5.png)

**Comment by palbrecht1** [comment]
Alternatively https://unpkg.com/browse/gelato-api@1.0.4/dist/types.d.ts shows the same content

**Comment by denkan** [comment]
Sorry, fixed in newly released 1.0.5
https://unpkg.com/browse/gelato-api@1.0.5/dist/types.d.ts
